### ISSUE TITLE
BUG: Restarting from failed not setting task run back to scheduled

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/ui#369]
**Bug Description**
When restarting a flow run from failed the task run that was failed stays in a failed state and thus will not restart properly.

**Steps To Reproduce**

Flow:

```python
from prefect import task, Flow

@task
def fail():
    raise ValueError()

with Flow("Restart Me") as flow:
    fail()
```

First run logs:

```
[2020-10-22 21:37:02] INFO - prefect.CloudFlowRunner | Beginning Flow run for 'Restart Me'
[2020-10-22 21:37:02] DEBUG - prefect.CloudFlowRunner | Using executor type LocalExecutor
[2020-10-22 21:37:02] DEBUG - prefect.CloudFlowRunner | Flow 'Restart Me': Handling state change from Scheduled to Running
[2020-10-22 21:37:03] INFO - prefect.CloudTaskRunner | Task 'fail': Starting task run...
[2020-10-22 21:37:03] DEBUG - prefect.CloudTaskRunner | Task 'fail': Handling state change from Pending to Running
[2020-10-22 21:37:03] DEBUG - prefect.CloudTaskRunner | Task 'fail': Calling task.run() method...
[2020-10-22 21:37:03] ERROR - prefect.CloudTaskRunner | Unexpected error: ValueError()
Traceback (most recent call last):
  File "/Users/josh/Desktop/code/prefect/src/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/Users/josh/Desktop/code/prefect/src/prefect/engine/task_runner.py", line 849, in get_task_run_state
    logger=self.logger,
  File "/Users/josh/Desktop/code/prefect/src/prefect/utilities/executors.py", line 298, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "restartme.py", line 22, in fail
    raise ValueError()
ValueError
[2020-10-22 21:37:03] DEBUG - prefect.CloudTaskRunner | Task 'fail': Handling state change from Running to Failed
[2020-10-22 21:37:03] INFO - prefect.CloudTaskRunner | Task 'fail': Finished task run for task with final state: 'Failed'
[2020-10-22 21:37:03] DEBUG - prefect.CloudFlowRunner | Checking flow run state...
[2020-10-22 21:37:03] INFO - prefect.CloudFlowRunner | Flow run FAILED: some reference tasks failed.
[2020-10-22 21:37:03] DEBUG - prefect.CloudFlowRunner | Flow 'Restart Me': Handling state change from Running to Failed
```

Click `RESTART` button on flow run page.

Second run logs:

```
[2020-10-22 21:37:29] INFO - prefect.CloudFlowRunner | Beginning Flow run for 'Restart Me'
[2020-10-22 21:37:29] DEBUG - prefect.CloudFlowRunner | Using executor type LocalExecutor
[2020-10-22 21:37:29] DEBUG - prefect.CloudFlowRunner | Flow 'Restart Me': Handling state change from Scheduled to Running
[2020-10-22 21:37:29] DEBUG - prefect.CloudFlowRunner | Checking flow run state...
[2020-10-22 21:37:30] INFO - prefect.CloudFlowRunner | Flow run FAILED: some reference tasks failed.
[2020-10-22 21:37:30] DEBUG - prefect.CloudFlowRunner | Flow 'Restart Me': Handling state change from Running to Failed
```

In the logs we should be seeing that the `fail` task runs and the value error is raised again however that does not happen.

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

**Comment by cicdw** [comment]
Note here: whatever fix is required, we should be sure and QA against the scenario of upstream mapped children and needing to restart (see https://github.com/PrefectHQ/ui/issues/182 and https://github.com/PrefectHQ/ui/pull/187)
