### ISSUE TITLE
BUG: Whitescreen with 0.14.6 (OktaAuth error)

### ISSUE THREAD

**Issue by sti0** [PrefectHQ/ui#588]
**Bug Description**

I upgraded my prefect installation on my Windows laptop to latest 0.14.6 version. Now if I navigate to the UI I get a white screen. Nothing loads. The following error is printed out in console:

```
Uncaught AuthSdkError: No issuer passed to constructor. Required usage: new OktaAuth({issuer: "https://{yourOktaDomain}.com/oauth2/{authServerId}"})
    at http://localhost:8080/js/defaultVendors~app~253ae210.2d09f131.js:287:48
    at new e (http://localhost:8080/js/defaultVendors~app~253ae210.2d09f131.js:287:780)
    at r.<anonymous> (http://localhost:8080/js/defaultVendors~app~253ae210.2d09f131.js:356:84)
    at new r (http://localhost:8080/js/defaultVendors~app~253ae210.2d09f131.js:356:201)
    at Object.4360 (http://localhost:8080/js/app~d0ae3f07.621724be.js:1:52687)
    at s (http://localhost:8080/js/app~d0ae3f07.621724be.js:1:595)
    at Object.ca94 (http://localhost:8080/js/app~d0ae3f07.621724be.js:1:236587)
    at s (http://localhost:8080/js/app~d0ae3f07.621724be.js:1:595)
    at Module.56d7 (http://localhost:8080/js/app~d0ae3f07.621724be.js:1:110723)
    at s (http://localhost:8080/js/app~d0ae3f07.621724be.js:1:595)
```

I already cleared cache & cookies and restarted the browser but it doesn't work. After a downgrade to 0.14.5 the UI works again.

**Steps To Reproduce**

1. Install / Upgrade to 0.14.6
2. `prefect backend server`
3. `prefect server start`
4. Open localhost:8080 in browser
5. F12 for dev console

**Browsers Tested:**
* [x] Chrome v88.0.4324.146
* [ ] Firefox
* [ ] Safari
* [x] Edge v86.0.622.38
* [ ] IE

----------
**Notes**

**Comment by rexliu0715** [comment]
+1

**Comment by Bbaranowski** [comment]
The same in Firefox 85.0 (Ubuntu)

**Comment by peterroelants** [comment]
+1, Similar issue as a few days ago: https://github.com/PrefectHQ/ui/issues/582

**Comment by znicholasbrown** [comment]
@peterroelants @rexliu0715 - please re-pull the 0.14.6 UI image when you're able and give that a test; the image was missing some required environment variables. Master pulls should work as well but are discouraged unless you're actively developing on the UI as features in the master branch are not guaranteed to be complete/working.

**Comment by peterroelants** [comment]
@znicholasbrown I can confirm that re-pulling `prefecthq/ui:core-0.14.6` fixes the issue
